import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {entity,clone,counts,withinBounds,validate,documentOf,decode,encode,argb,hexColor,LIMITS,versionOf} from './model.js';
import {geometry,material} from './geometry.js';
import {prepareImages,importPhoto} from './images.js';
import {History,pivotOf,transformSelection,duplicateSelection,eraseStroke,shapeEntity} from './editing.js';
import {PAPER_TYPES,paperPixels,basis,rotate,insidePaper,attachedIds,paperCoordinates,worldPoint,paperAxes,surfaceWorld,strokeUV,localizePapers,hitPaper,bendPoint} from './paper.js';
import {smoothPoints} from './stroke-processing.js';
import {strokeCapacity,assistedStrokeScene,sheetEndpoints,closestEndpoint} from './drawing-assists.js';
const $=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)];
const names={draw:'Freehand drawing',line:'Straight line',curve:'Curve drawing',rectangle:'Rectangle',ellipse:'Ellipse',block:'Solid block',select:'Object selection',marquee:'Box selection',move:'Move selection',erase:'Eraser',orbit:'Orbit view',panorama:'Panorama preview',start:'Place Start',checkpoint:'Place Checkpoint',goal:'Place Goal'};
const keys={d:'draw',v:'select',b:'marquee',m:'move',e:'erase',l:'line',q:'curve',r:'rectangle',c:'ellipse',g:'block',o:'orbit'};
const hints={draw:'Drag to draw · Right-drag to orbit',line:'Drag a line · Shift snaps to 15°',curve:'Drag endpoints · Bend sets the arc · Shift snaps to 15°',rectangle:'Drag a rectangle · Shift makes a square',ellipse:'Drag an ellipse · Shift makes a circle',block:'Drag a base · Set depth in the inspector',select:'Click to select · Shift toggles · B box selects',marquee:'Drag a selection box · Shift adds · Ctrl subtracts',move:'Drag selected objects · Esc cancels',erase:'Drag to erase · One drag = one undo',orbit:'Drag to orbit · Wheel zooms · Middle-drag pans',panorama:'Drag to look around · Arrow keys turn · Esc returns to drawing'};
let panoramaView=null;let activePaperId='';const paperTextures=new Map();
let entities=[],selected=new Set(),tool='draw',dirty=false,projectName='Untitled scene',busy=false,images=new Map(),gesture=null,game=null,raf=0,toastTimer;
const history=new History(),brush={brush:'Pen',pattern:'solid',color:argb('#7ee8c5'),width:.018,alpha:1,wet:false};
const scene=new THREE.Scene();scene.background=new THREE.Color('#11191c');
const camera=new THREE.PerspectiveCamera(48,1,.02,100);camera.position.set(0,1.4,5);
const canvas=$('canvas');let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch{$('welcome').innerHTML='<h1>WebGL 2 is needed.</h1><p>Enable hardware acceleration and use a current browser.</p>';throw new Error('WebGL 2 unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));
const controls=new OrbitControls(camera,canvas);controls.target.set(0,1.4,0);controls.minDistance=.3;controls.maxDistance=20;controls.enableDamping=false;controls.update();
const group=new THREE.Group();scene.add(group);
const floorGrid=new THREE.GridHelper(8,16,0x49665e,0x253c38);scene.add(floorGrid);
const axes=new THREE.AxesHelper(.35);axes.material.depthTest=false;axes.renderOrder=3;scene.add(axes);
const guide=new THREE.GridHelper(6,12,0x406354,0x294239);guide.material.transparent=true;guide.material.opacity=.3;guide.material.depthWrite=false;scene.add(guide);
const selectionBox=new THREE.Box3Helper(new THREE.Box3(),0x9adcbc);selectionBox.material.depthTest=false;selectionBox.renderOrder=5;selectionBox.visible=false;scene.add(selectionBox);
const sheetOutline=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0x7ee8c5,transparent:true,opacity:.65,dashSize:.035,gapSize:.025,depthTest:false,depthWrite:false}));sheetOutline.renderOrder=4;sheetOutline.visible=false;scene.add(sheetOutline);let outlinePaper=null;
const mirrorGuide=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:0xf3c179,transparent:true,opacity:.8,dashSize:.025,gapSize:.02,depthTest:false,depthWrite:false}));mirrorGuide.renderOrder=4;mirrorGuide.visible=false;scene.add(mirrorGuide);let mirrorGuideKey='';
const meshes=new Map(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const snapshot=()=>({entities,selected:new Set(selected),activePaperId}),selectedEntities=()=>entities.filter(e=>selected.has(e.id)),selectedEntity=()=>selected.size===1?selectedEntities()[0]:null;
function notify(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:4000);}
function requestFrame(){if(!raf&&!document.hidden)raf=requestAnimationFrame(render);}
function render(now){raf=0;let animating=false;for(const record of meshes.values())if(record.born){const t=Math.min(1,(now-record.born)/4000);record.mesh.material.userData.growth.value=1-(1-t)**2;if(t<1)animating=true;else record.born=0;}renderer.render(scene,camera);if(animating)requestFrame();}
function updateGuide(){
  const mode=$('plane').value,offset=Number($('offset').value)/100;$('offset-value').textContent=offset.toFixed(2)+' m';guide.rotation.set(0,0,0);guide.position.set(0,0,0);
  if(mode==='wall'){guide.rotation.x=Math.PI/2;guide.position.set(0,1.5,offset);}else if(mode==='floor')guide.position.y=offset+.002;else if(mode==='side'){guide.rotation.z=Math.PI/2;guide.position.set(offset,1.5,0);}else{guide.position.copy(controls.target).addScaledVector(camera.getWorldDirection(new THREE.Vector3()),-offset);guide.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),camera.getWorldDirection(new THREE.Vector3()).negate());}
  $('plane-label').textContent=activePaper()?'PAPER · '+PAPER_TYPES[activePaper().paperKind].name:({wall:'WALL · Z',floor:'FLOOR · Y',side:'SIDE · X',view:'VIEW OFFSET'}[mode])+` = ${offset.toFixed(2)} m`;guide.visible=!game&&!activePaper()&&$('workspace-guides').checked;requestFrame();
}
controls.addEventListener('change',()=>{updateGuide();requestFrame();});
new ResizeObserver(()=>{const box=$('viewport').getBoundingClientRect();if(!box.width||!box.height)return;const aspect=box.width/box.height,ratio=Math.max(1,1/aspect)/Math.max(1,1/camera.aspect);if(!panoramaView)camera.position.sub(controls.target).multiplyScalar(ratio).add(controls.target);camera.aspect=aspect;camera.updateProjectionMatrix();renderer.setSize(box.width,box.height,false);if(panoramaView)updatePanorama();else controls.update();requestFrame();}).observe($('viewport'));
document.addEventListener('visibilitychange',()=>{if(document.hidden){finishGesture();if(raf){cancelAnimationFrame(raf);raf=0;}}else requestFrame();});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();finishGesture(true);notify('Graphics paused. Your scene is still in memory; export if recovery fails.',true);});canvas.addEventListener('webglcontextrestored',()=>{notify('Graphics restored.');requestFrame();});
function paperTexture(kind,ink=false){const key=kind+':'+ink;if(paperTextures.has(key))return paperTextures.get(key);const {pixels,size}=paperPixels(kind,ink),t=new THREE.DataTexture(pixels,size,size);t.flipY=false;t.minFilter=t.magFilter=THREE.LinearFilter;if(!ink)t.colorSpace=THREE.SRGBColorSpace;t.userData.shared=true;t.needsUpdate=true;paperTextures.set(key,t);return t;}
function activePaper(){return entities.find(e=>e.id===activePaperId&&e.type==='paper');}
function updateVisibility(){
  const p=activePaper(),focus=!!p&&!game&&($('focus-sheet').checked||!!panoramaView),ghost=$('see-through').checked&&!game&&!panoramaView;
  for(const [id,record] of meshes){
    record.mesh.visible=(record.entity.type!=='paper'||record.entity.paperVisible!==false)&&(!focus||id===p.id||record.entity.paperId===p.id);
    if(record.entity.type==='paper'){const m=record.mesh.material;if(m.transparent!==ghost){m.transparent=ghost;m.needsUpdate=true;}m.opacity=ghost?.14:1;m.depthWrite=!ghost;record.mesh.renderOrder=ghost?-1:0;}
  }
  updateSheetOutline(p);updateMirrorGuide(p);floorGrid.visible=axes.visible=!panoramaView&&$('workspace-guides').checked;$('sheet-focus-banner').hidden=!focus||!!panoramaView;$('panorama-banner').hidden=!panoramaView;if(p)$('sheet-focus-label').textContent='Focused on sheet '+(entities.filter(e=>e.type==='paper').indexOf(p)+1);
}
// The outline is an editor aid, never a pickable or exported object. Only rebuild on sheet edits.
function updateSheetOutline(p){
  sheetOutline.visible=!!p&&(p.paperVisible===false||$('see-through').checked)&&!game&&!panoramaView&&tool!=='orbit'&&(['draw','line','curve','rectangle','ellipse'].includes(tool)||selected.has(p.id));
  if(!sheetOutline.visible||outlinePaper===p)return;
  const positions=[],w=p.panelWidth/2,h=p.panelWidth/p.aspect/2,n=Math.max(1,Math.ceil(Math.abs(p.bend)/3));
  const edge=(a,b)=>positions.push(...bendPoint(p,a,.005/p.scale),...bendPoint(p,b,.005/p.scale));
  for(let i=0;i<n;i++)for(const y of [-h,h])edge([-w+2*w*i/n,y],[-w+2*w*(i+1)/n,y]);
  for(const x of [-w,w])edge([x,-h],[x,h]);
  sheetOutline.geometry.dispose();sheetOutline.geometry=new THREE.BufferGeometry();sheetOutline.geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));sheetOutline.computeLineDistances();setMeshPose(sheetOutline,p,null);outlinePaper=p;
}
function updateMirrorGuide(p){
  const axis=$('mirror-strokes').value;mirrorGuide.visible=!!p&&axis!=='off'&&!game&&!panoramaView&&['draw','line','curve','rectangle','ellipse'].includes(tool);
  if(!mirrorGuide.visible)return;const key=JSON.stringify([p,axis]);if(key===mirrorGuideKey)return;
  const positions=[],n=axis==='v'?Math.max(1,Math.ceil(Math.abs(p.bend)/3)):1;
  for(let i=0;i<=n;i++){const uv=axis==='u'?[0,(i/n-.5)*p.panelWidth/p.aspect]:[(i/n-.5)*p.panelWidth,0];positions.push(...bendPoint(p,uv,.006/p.scale));}
  mirrorGuide.geometry.dispose();mirrorGuide.geometry=new THREE.BufferGeometry();mirrorGuide.geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));mirrorGuide.computeLineDistances();setMeshPose(mirrorGuide,p,null);mirrorGuideKey=key;
}
function dispose(record){record.mesh.geometry.dispose();if(!record.mesh.material.map?.userData.shared)record.mesh.material.map?.dispose();record.mesh.material.dispose();group.remove(record.mesh);}
function setMeshPose(mesh,e,paper){const parent=paper||(e.type==='paper'?e:null),pose=parent||e;mesh.position.fromArray(pose.position);mesh.rotation.y=pose.yaw*Math.PI/180;mesh.scale.setScalar(pose.scale);if(parent){const a=paperAxes(parent),matrix=new THREE.Matrix4().makeBasis(new THREE.Vector3(...rotate(a.u,parent.yaw)),new THREE.Vector3(...rotate(a.v,parent.yaw)),new THREE.Vector3(...rotate(a.n,parent.yaw)));mesh.quaternion.setFromRotationMatrix(matrix);}}
function sheetMeshKey(p,e){return p&&[p.bend,p.panelWidth,p.aspect,p.paperKind,p.scale,...(e.wet&&p.paperKind==='coated'?[p.pitch,p.roll,...p.normal]:[])].join(':');}
function syncMeshes(animatedId){
  const animatedIds=new Set(Array.isArray(animatedId)?animatedId:animatedId?[animatedId]:[]);
  const ids=new Set(entities.map(e=>e.id));for(const [id,record] of meshes)if(!ids.has(id)){dispose(record);meshes.delete(id);}
  for(const e of entities){const paper=e.paperId?entities.find(p=>p.id===e.paperId):null,old=meshes.get(e.id);if(old?.entity===e&&old?.paper===paper&&!animatedIds.has(e.id))continue;if(old?.entity===e&&!animatedIds.has(e.id)&&(e.pointSpace==='surface'||e.type==='paper')&&old.sheetKey===sheetMeshKey(paper||(e.type==='paper'?e:null),e)){setMeshPose(old.mesh,e,paper);old.paper=paper;continue;}const born=animatedIds.has(e.id)&&e.wet&&(!paper||paper.paperKind==='coated')?performance.now():old?.born||0;if(old)dispose(old);
    let texture;if(e.type==='image'){texture=new THREE.Texture(images.get(e.image));texture.colorSpace=THREE.SRGBColorSpace;texture.flipY=false;texture.needsUpdate=true;}
    if(e.type==='paper')texture=paperTexture(e.paperKind);else if(paper)texture=paperTexture(paper.paperKind,true);
    const mesh=new THREE.Mesh(geometry(e,paper),material(e,texture,paper|| (e.type==='paper'?e:null)));setMeshPose(mesh,e,paper);mesh.userData.id=e.id;
    if(born||gesture?.entity?.id===e.id||gesture?.mirrorId===e.id)mesh.material.userData.growth.value=0;group.add(mesh);meshes.set(e.id,{mesh,entity:e,paper,born,sheetKey:sheetMeshKey(paper||(e.type==='paper'?e:null),e)});
  }updateVisibility();group.updateMatrixWorld(true);updateSelectionBox();requestFrame();
}
function updateSelectionBox(){selectionBox.box.makeEmpty();for(const id of selected){const mesh=meshes.get(id)?.mesh;if(mesh&&(mesh.visible||entities.find(e=>e.id===id)?.type==='paper'))selectionBox.box.union(new THREE.Box3().setFromObject(mesh));}selectionBox.visible=!selectionBox.box.isEmpty()&&!game;if(selectionBox.visible)selectionBox.box.expandByScalar(.025);}
function setDirty(value=true){dirty=value;$('save-state').textContent=value?'Not exported':'Exported / opened';$('save-dot').style.background=value?'#d2ac75':'#7ee8c5';}
function label(e){return e.type==='stroke'?`${e.brush}${e.pattern&&e.pattern!=='solid'?' · '+e.pattern:''} stroke`:({paper:PAPER_TYPES[e.paperKind]?.name+(e.paperVisible===false?' guide · hidden':' paper'),image:'Curved image',block:'Solid block',start:'Start',checkpoint:'Checkpoint',goal:'Goal'}[e.type]);}
function updateUI(){
  const c=counts(entities);$('welcome').hidden=entities.length>0;$('project-name').textContent=projectName;$('object-count').textContent=`${c.objects} / 80`;$('budget').textContent=`${c.points.toLocaleString()} points / 4,000 · ${c.images} images / 6`;$('format-status').textContent=versionOf(entities)===5?'INK GUIDES V5 · ANDROID 0.6+':versionOf(entities)===4?'SURFACE FORMAT V4 · ANDROID 0.5+':versionOf(entities)===3?'PAPER FORMAT V3 · ANDROID 0.3+':versionOf(entities)===2?'PHONE FORMAT V2 · ANDROID 0.2+':'PHONE-COMPATIBLE · V1';
  $('undo').disabled=!history.past.length||!!game;$('redo').disabled=!history.future.length||!!game;$('undo').title=`Undo ${history.past.at(-1)?.label||''} (Ctrl+Z)`;$('redo').title=`Redo ${history.future.at(-1)?.label||''} (Ctrl+Shift+Z)`;$('history-status').textContent=history.past.length?`${history.past.at(-1).label} · ${history.past.length} undo steps`:'Ready to create';$('selection-actions').hidden=!selected.size||!!game;$('selection-count').textContent=`${selected.size} selected`;
  const target=$('painting-target');if(!activePaper())activePaperId='';target.replaceChildren(new Option('Free 3D space',''));entities.filter(e=>e.type==='paper').forEach((p,i)=>target.add(new Option(`${i+1} · ${PAPER_TYPES[p.paperKind].name}${p.paperVisible===false?' · hidden guide':''}`,p.id)));target.value=activePaperId;
  const list=$('outliner');list.replaceChildren();if(!entities.length){const p=document.createElement('p');p.className='hint';p.textContent='Your strokes, shapes and images appear here.';list.append(p);}
  entities.forEach((e,i)=>{const b=document.createElement('button');b.className='object-row'+(selected.has(e.id)?' active':'');b.setAttribute('aria-label',`${label(e)} ${i+1}`);b.setAttribute('aria-pressed',String(selected.has(e.id)));const icon=document.createElement('span');icon.className='object-icon';icon.style.color=hexColor(e.color);icon.textContent=({paper:'▤',stroke:'╱',image:'▧',block:'⬡',start:'▷',checkpoint:'◉',goal:'⚑'}[e.type]);const name=document.createElement('span');name.textContent=label(e);const count=document.createElement('small');count.textContent=String(i+1).padStart(2,'0');b.append(icon,name,count);b.onclick=event=>{if(game||busy)return;setTool('select');select(e.id,event.shiftKey);};list.append(b);});updateGuide();updateInspector();updateVisibility();updateSelectionBox();requestFrame();
}
function updateInspector(){
  const chosen=selectedEntities(),e=selectedEntity(),style=chosen.find(e=>e.type==='stroke')||e||brush;
  $('tool-name').textContent=names[tool];$('tool-key').textContent=Object.keys(keys).find(k=>keys[k]===tool)?.toUpperCase()||'MAP';$('tool-hint').textContent=hints[tool]||'Click to place a marker';$('curve-options').hidden=tool!=='curve';$('smooth-selected').disabled=!chosen.some(e=>e.type==='stroke'&&e.points.length>2)||!!game||busy;$('erase-options').hidden=tool!=='erase';$('block-options').hidden=tool!=='block';$('paint-options').hidden=['erase','orbit','panorama'].includes(tool);$('selection-panel').hidden=!chosen.length||!!game;
  if(chosen.length){const pivot=pivotOf(entities,selected);$('selection-name').textContent=e?label(e):`${chosen.length} objects`;['x','y','z'].forEach((axis,i)=>$('pos-'+axis).value=+pivot[i].toFixed(3));$('yaw').value=e?e.yaw:0;$('scale').value=e?+e.scale.toFixed(3):1;$('selection-hint').textContent=e?'M: drag to move · Shift-click: add to selection':'Position moves the group. Yaw adds a rotation; scale multiplies around the group centre.';}
  const paper=e?.type==='paper'?e:activePaper();if(paper)$('paper-kind').value=paper.paperKind;const kind=$('paper-kind').value;$('paper-description').textContent=PAPER_TYPES[kind].description;$('paper-swatch').dataset.kind=kind;$('paper-fields').hidden=e?.type!=='paper';$('edit-surface').disabled=!activePaper();const active=activePaper();for(const id of ['sheet-nearer','sheet-farther','parallel-sheet','mirror-strokes','snap-ends'])$(id).disabled=!active||!!game||!!panoramaView;$('drawing-assists-note').textContent=active?'Mirror uses the sheet centre. Snap ends joins strokes on this sheet. Both work on curved or hidden guides.':'Add or choose a sheet to use mirror, endpoint snapping and depth controls.';$('toggle-paper').disabled=!active||!!game;$('toggle-paper').textContent=active?.paperVisible===false?'Show sheet':'Hide sheet · keep ink';$('toggle-paper').setAttribute('aria-pressed',String(active?.paperVisible===false));$('view-ink').disabled=!entities.some(e=>e.type==='paper')||!!game;$('show-papers').disabled=!entities.some(e=>e.type==='paper'&&e.paperVisible===false)||!!game;$('paper-visibility-note').textContent=active?.paperVisible===false?'Hidden guide: ink stays editable. Draw inside the dotted frame, or Orbit to see only the ink.':'Hide the sheet to leave its ink floating in 3D. You can show the sheet again at any time.';$('delete').textContent=chosen.some(e=>e.type==='paper')?'Delete sheet + ink':'Delete';$('active-paper-bend').disabled=!active;$('active-paper-bend').value=active?.bend||0;$('active-paper-bend-value').textContent=(active?.bend||0)+'°'+(!active?.bend?' · Flat':'');$('focus-sheet').disabled=!active||!!panoramaView;$('face-and-draw').disabled=!active;$('preview-panorama').disabled=!active||active.bend<30;$('preview-panorama').title=active?.bend>=30?'Look around from the centre of this curved sheet':'Choose Curved monitor or Panorama first';$$('[data-paper-bend]').forEach(b=>{b.disabled=!active;b.classList.toggle('active',!!active&&(active.bend||0)===Number(b.dataset.paperBend));});if(e?.type==='paper'){$('paper-width').value=+e.panelWidth.toFixed(3);$('paper-height').value=+(e.panelWidth/e.aspect).toFixed(3);for(const key of ['bend','pitch','roll'])$('surface-'+key).value=e[key]||0;$('surface-bend-value').textContent=(e.bend||0)+'°';}$('pos-z').disabled=!!e?.paperId;if(e?.paperId)$('selection-hint').textContent='X/Y and rotation are on this sheet. Select its paper to move it through 3D space.';
  $('image-fields').hidden=e?.type!=='image';$('block-fields').hidden=e?.type!=='block';if(e?.type==='image'){$('arc').value=e.arc;$('arc-value').textContent=e.arc+'°';$('panel-width').value=e.panelWidth;}if(e?.type==='block')['x','y','z'].forEach((axis,i)=>$('size-'+axis).value=+e.size[i].toFixed(3));
  $$('[data-brush]').forEach(b=>{b.classList.toggle('active',b.dataset.brush===style.brush);b.setAttribute('aria-pressed',String(b.dataset.brush===style.brush));});$('color').value=hexColor(style.color);$('color-value').textContent=hexColor(style.color).toUpperCase();$$('[data-color]').forEach(b=>b.classList.toggle('active',b.dataset.color===hexColor(style.color)));$('width').value=style.width*1000;$('width-value').textContent=Math.round(style.width*1000)+' mm';$('opacity').value=style.alpha*100;$('opacity-value').textContent=Math.round(style.alpha*100)+'%';$('wet').checked=style.wet;$('pattern').value=style.pattern||'solid';
}
function select(id,toggle=false){const item=entities.find(e=>e.id===id);if(item?.type==='paper')activePaperId=id;else if(item?.paperId)activePaperId=item.paperId;else if(item)$('focus-sheet').checked=false;selected=toggle?new Set(selected):new Set();if(id){if(toggle&&selected.has(id))selected.delete(id);else selected.add(id);}updateUI();}
function restore(state){entities=state.entities;selected=new Set(state.selected);activePaperId=state.activePaperId||'';syncMeshes();updateUI();}
function commit(next,label,before=snapshot(),nextSelection=selected,animatedId,paintTarget=activePaperId){validate(documentOf(next));const after={entities:next,selected:new Set([...nextSelection].filter(id=>next.some(e=>e.id===id))),activePaperId:next.some(e=>e.id===paintTarget&&e.type==='paper')?paintTarget:''};if(before.entities!==next){history.push(before,after,label);setDirty();}entities=after.entities;selected=after.selected;activePaperId=after.activePaperId;syncMeshes(animatedId);updateUI();}
function editSelected(label,change,filter=()=>true){if(!selected.size||game||busy)return;leavePanorama(false);try{let changed=false;const next=localizePapers(entities,new Set(entities.filter(e=>selected.has(e.id)&&e.type==='paper').map(e=>e.id))).map(e=>{if(!selected.has(e.id)||!filter(e))return e;const copy=clone(e);change(copy);changed=true;return copy;});if(changed)commit(next,label);}catch(error){notify(error.message,true);updateInspector();}}
async function exclusive(work){if(busy)return;leavePanorama();finishGesture();busy=true;document.body.classList.add('busy');controls.enabled=false;try{await work();}catch(error){notify(error.message,true);}finally{busy=false;document.body.classList.remove('busy');controls.enabled=true;requestFrame();}}
async function travelHistory(back){if(game)return;await exclusive(async()=>{const next=history.peek(back);if(!next)return;const prepared=await prepareImages(next.entities,images);history.travel(back);images=prepared;restore(next);setDirty();});}
function setTool(next,internal=false){$('snap-cursor').hidden=true;if(busy&&!internal)return;leavePanorama(false);finishGesture();if(game)stopGame();tool=next;if(['block','start','checkpoint','goal'].includes(next))$('focus-sheet').checked=false;if(['draw','line','curve','rectangle','ellipse','block','start','checkpoint','goal'].includes(next))selected=new Set();if(next==='block'&&$('plane').value==='view'){$('plane').value='wall';updateGuide();notify('Blocks use map axes. Drawing plane changed to Wall.');}
  $$('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===next);b.setAttribute('aria-pressed',String(b.dataset.tool===next));});controls.mouseButtons={LEFT:next==='orbit'?THREE.MOUSE.ROTATE:null,MIDDLE:THREE.MOUSE.PAN,RIGHT:THREE.MOUSE.ROTATE};controls.touches.ONE=next==='orbit'?THREE.TOUCH.ROTATE:null;controls.touches.TWO=next==='orbit'?THREE.TOUCH.DOLLY_PAN:null;canvas.style.cursor=next==='orbit'?'grab':next==='select'?'default':next==='move'?'move':next==='erase'?'none':'crosshair';$('eraser-cursor').hidden=true;updateUI();
}
function ray(event){const r=canvas.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);camera.updateMatrixWorld();raycaster.setFromCamera(pointer,camera);return raycaster.ray;}
function mapPlane(){const mode=$('plane').value,offset=Number($('offset').value)/100;if(mode==='wall')return new THREE.Plane(new THREE.Vector3(0,0,1),-offset);if(mode==='floor')return new THREE.Plane(new THREE.Vector3(0,1,0),-offset);if(mode==='side')return new THREE.Plane(new THREE.Vector3(1,0,0),-offset);const normal=camera.getWorldDirection(new THREE.Vector3()).negate();return new THREE.Plane().setFromNormalAndCoplanarPoint(normal,controls.target.clone().addScaledVector(normal,offset));}
function drawingPlane(){return mapPlane();}
function planeBasis(plane){if(activePaper()&&['draw','line','curve','rectangle','ellipse'].includes(tool))return {u:[1,0,0],v:[0,1,0],normal:[0,0,1]};const n=plane.normal.clone();let u;if($('plane').value==='view')u=new THREE.Vector3(1,0,0).applyQuaternion(camera.quaternion);else u=Math.abs(n.x)>.9?new THREE.Vector3(0,0,-1):new THREE.Vector3(1,0,0);return {u:u.toArray(),v:new THREE.Vector3().crossVectors(n,u).normalize().toArray(),normal:n.toArray()};}
function hitPlane(event,plane,bounded=true){const r=ray(event),paper=activePaper();if(bounded&&paper&&['draw','line','curve','rectangle','ellipse'].includes(tool)){const hit=hitPaper(paper,r.origin.toArray(),r.direction.toArray());return hit?new THREE.Vector3(...hit.uv):null;}const hit=r.intersectPlane(plane,new THREE.Vector3());return hit&&(!bounded||hit.length()<=3.6)?hit:null;}
function snappedInput(event,point,grid=false){
  $('snap-cursor').hidden=true;const p=activePaper(),enabled=gesture?.snapEnabled??$('snap-ends').checked;
  if(p&&enabled&&!game&&!busy&&['draw','line','curve'].includes(tool)&&!event.shiftKey){
    const candidates=gesture?.snapCandidates||sheetEndpoints(entities,p),origin=camera.position.toArray();
    const found=closestEndpoint(candidates,screenPoint(event),uv=>{const world=surfaceWorld(p,uv),screen=screenWorld(world);if(!screen)return null;const direction=new THREE.Vector3(...world).sub(camera.position).normalize().toArray(),hit=hitPaper(p,origin,direction);return hit&&Math.hypot(hit.uv[0]-uv[0],hit.uv[1]-uv[1])<.0001?screen:null;},event.pointerType==='touch'?22:14);
    if(found){const marker=$('snap-cursor');marker.hidden=false;marker.style.left=found.screen[0]+'px';marker.style.top=found.screen[1]+'px';return {point:new THREE.Vector3(...found.uv),snapped:true};}
  }
  return {point:grid?snapPoint(point):point,snapped:false};
}
function snapPoint(p){return $('snap').checked?p.clone().multiplyScalar(10).round().multiplyScalar(.1):p;}
function screenPoint(event){const r=canvas.getBoundingClientRect();return [event.clientX-r.left,event.clientY-r.top];}
function screenWorld(world){const v=new THREE.Vector3(...world),depth=-v.clone().applyMatrix4(camera.matrixWorldInverse).z;if(depth<=.02)return null;const clip=v.project(camera);if(clip.z>1)return null;return [(clip.x+1)*canvas.clientWidth/2,(1-clip.y)*canvas.clientHeight/2,depth];}
function project(e,p){const paper=entities.find(q=>q.id===e.paperId);return screenWorld(paper?surfaceWorld(paper,strokeUV(e,p,paper),.003/paper.scale):worldPoint(e,p));}
function worldPivot(){const chosen=selectedEntities().filter(e=>!selected.has(e.paperId));return [0,1,2].map(i=>chosen.reduce((sum,e)=>{const p=entities.find(q=>q.id===e.paperId);return sum+(p?surfaceWorld(p,strokeUV(e,[0,0,0],p))[i]:e.position[i]);},0)/chosen.length);}
function eraserSamples(e){const paper=entities.find(p=>p.id===e.paperId);if(!paper?.bend||e.points.length<2)return e.points;const extra=1024,segments=e.points.slice(1).map((p,i)=>Math.abs(strokeUV(e,p,paper)[0]-strokeUV(e,e.points[i],paper)[0])),length=segments.reduce((a,b)=>a+b,0),step=Math.max(paper.panelWidth*3/Math.abs(paper.bend),length/extra);return e.points.flatMap((b,i)=>{if(!i)return [b];const a=e.points[i-1],n=Math.max(1,Math.ceil(segments[i-1]/step));return Array.from({length:n},(_,j)=>a.map((v,k)=>v+(b[k]-v)*(j+1)/n));});}
function pick(event){ray(event);group.updateMatrixWorld(true);const hit=raycaster.intersectObjects(group.children.filter(m=>m.visible),false).find(h=>{const e=entities.find(e=>e.id===h.object.userData.id);return !e?.paperId||h.uv&&h.uv.x>=0&&h.uv.x<=1&&h.uv.y>=0&&h.uv.y<=1;});let id=hit?.object.userData.id||null,distance=hit?.distance??Infinity;for(const e of entities)if(['start','checkpoint','goal'].includes(e.type)&&meshes.get(e.id)?.mesh.visible){const p=raycaster.ray.intersectSphere(new THREE.Sphere(new THREE.Vector3(...e.position),.2*e.scale),new THREE.Vector3());if(p){const d=p.distanceTo(raycaster.ray.origin);if(d<distance){id=e.id;distance=d;}}}return id;}
function startGesture(kind,event,extra={}){const paper=activePaper(),mirror=paper&&['draw','line','curve','rectangle','ellipse'].includes(kind)?$('mirror-strokes').value:'off';gesture={paper,mirror,mirrorId:crypto.randomUUID(),pointBudget:strokeCapacity(entities,mirror!=='off'),snapEnabled:$('snap-ends').checked,snapCandidates:sheetEndpoints(entities,paper),kind,pointerId:event.pointerId,before:snapshot(),startScreen:screenPoint(event),lastScreen:screenPoint(event),...extra};controls.enabled=false;canvas.setPointerCapture(event.pointerId);}
function markChanged(){syncMeshes();const c=counts(entities);$('object-count').textContent=`${c.objects} / 80`;$('budget').textContent=`${c.points.toLocaleString()} points / 4,000 · ${c.images} images / 6`;$('welcome').hidden=entities.length>0;}
function preview(next){try{validate(documentOf(next));entities=next;gesture.changed=true;gesture.error=null;markChanged();return true;}catch(error){gesture.error=error.message;return false;}}
function appendPoint(event,final=false){
  const g=gesture,e=g.entity,raw=hitPlane(event,g.plane);if(!raw)return;
  const hit=!e.points.length?{point:new THREE.Vector3(...e.position),snapped:false}:final?snappedInput(event,raw):{point:raw,snapped:false};
  const local=hit.point.sub(new THREE.Vector3(...e.position)),last=e.points.at(-1),pressure=event.pointerType==='pen'?Math.max(.1,Math.min(2,event.pressure*2||.1)):1;
  if(last&&!final)local.lerp(new THREE.Vector3(...last.slice(0,3)),Number($('smoothing').value)/100);
  const replace=last&&final&&local.distanceTo(new THREE.Vector3(...last.slice(0,3)))<Math.max(.004,e.width*.2);
  if(last&&!final&&local.distanceTo(new THREE.Vector3(...last.slice(0,3)))<Math.max(.004,e.width*.2))return;
  if(!replace&&e.points.length>=g.pointBudget){g.error='Stroke point limit reached. Start another stroke or remove content.';return;}
  const previous=e.points;e.points=replace?[...previous.slice(0,-1),[...local.toArray(),pressure]]:[...previous,[...local.toArray(),pressure]];
  if(!withinBounds(e)){e.points=previous;return;}const old=meshes.get(e.id);if(old)old.entity=null;
  try{preview(assistedStrokeScene(g.before.entities,e,g.paper,g.mirror,g.mirrorId));}catch(error){e.points=previous;g.error=error.message;}
}
function updateShape(event){
  const g=gesture;if(Math.hypot(...screenPoint(event).map((v,i)=>v-g.startScreen[i]))<3)return;const raw=hitPlane(event,g.plane);if(!raw)return;
  const hit=snappedInput(event,raw,true),e=shapeEntity(g.kind,g.start,hit.point.toArray(),g.basis,g.style,{depth:g.depth,constrain:event.shiftKey,bend:g.bend,curveKind:g.curveKind,pointBudget:Math.min(65,g.pointBudget)});e.id=g.id;
  try{if(preview(assistedStrokeScene(g.before.entities,e,g.paper,g.mirror,g.mirrorId))){g.entity=e;selected=new Set([e.id]);}}catch(error){g.error=error.message;}
}
function updateMarquee(event){const g=gesture,p=screenPoint(event),x=Math.min(p[0],g.startScreen[0]),y=Math.min(p[1],g.startScreen[1]),w=Math.abs(p[0]-g.startScreen[0]),h=Math.abs(p[1]-g.startScreen[1]);Object.assign($('marquee').style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});$('marquee').hidden=false;const found=[];group.updateMatrixWorld(true);
  for(const e of entities){const mesh=meshes.get(e.id)?.mesh;if(!mesh?.visible)continue;mesh.geometry.computeBoundingBox();const b=mesh.geometry.boundingBox,points=[];for(const xx of [b.min.x,b.max.x])for(const yy of [b.min.y,b.max.y])for(const zz of [b.min.z,b.max.z]){const p=screenWorld(new THREE.Vector3(xx,yy,zz).applyMatrix4(mesh.matrixWorld).toArray());if(p)points.push(p);}if(!points.length)continue;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);if(Math.max(...xs)>=x&&Math.min(...xs)<=x+w&&Math.max(...ys)>=y&&Math.min(...ys)<=y+h)found.push(e.id);}
  selected=new Set(g.add||g.subtract?g.before.selected:[]);for(const id of found){if(g.subtract)selected.delete(id);else selected.add(id);}updateSelectionBox();$('selection-actions').hidden=!selected.size;$('selection-count').textContent=`${selected.size} selected`;requestFrame();
}
function updateErase(event){const g=gesture,to=screenPoint(event),from=g.lastScreen;g.lastScreen=to;let next;
  if(g.mode==='object'){const picked=pick(event);next=entities.filter(e=>{if(g.scope.size&&!g.scope.has(e.id))return true;if(e.id===picked)return false;if(e.type==='stroke'){const chunks=eraseStroke(e,project,from,to,g.radius,eraserSamples(e));return chunks.length===1&&chunks[0]===e;}return true;});}
  else next=entities.flatMap(e=>{if(g.scope.size&&!g.scope.has(e.id))return [e];const chunks=eraseStroke(e,project,from,to,g.radius,eraserSamples(e));if(g.scope.has(e.id))for(const chunk of chunks)g.scope.add(chunk.id);return chunks;});
  if(g.mode==='object'){const surviving=new Set(next.filter(e=>e.type==='paper').map(e=>e.id));next=next.filter(e=>!e.paperId||surviving.has(e.paperId));}
  if(next.length===entities.length&&next.every((e,i)=>e===entities[i]))return;preview(next);
}
function updateMove(event){const g=gesture,p=hitPlane(event,g.plane,false);if(!p)return;let delta=p.sub(g.hit);if($('snap').checked)delta.multiplyScalar(10).round().multiplyScalar(.1);if(delta.lengthSq()<1e-10){preview(g.before.entities);return;}try{let move=delta.toArray();const chosen=g.before.entities.filter(e=>g.before.selected.has(e.id)),p=entities.find(e=>e.id===chosen[0]?.paperId);if(p&&chosen.every(e=>e.paperId===p.id)){const a=paperCoordinates(p,g.hit.toArray()),b=paperCoordinates(p,g.hit.clone().add(delta).toArray());move=[b[0]-a[0],b[1]-a[1],0];}preview(transformSelection(g.before.entities,g.before.selected,{move}));}catch(error){g.error=error.message;}}
function updateGesture(event){if(!gesture||gesture.pointerId!==event.pointerId)return;if(gesture.kind==='draw')appendPoint(event);else if(gesture.kind==='marquee')updateMarquee(event);else if(gesture.kind==='erase')updateErase(event);else if(gesture.kind==='move')updateMove(event);else updateShape(event);}
function finishGesture(cancel=false){if(!gesture)return;const g=gesture;gesture=null;if(canvas.hasPointerCapture(g.pointerId))canvas.releasePointerCapture(g.pointerId);controls.enabled=!busy;$('marquee').hidden=true;$('snap-cursor').hidden=true;if(cancel){restore(g.before);return;}if(g.kind==='marquee'){updateUI();return;}
  if(g.kind==='draw'&&g.postSmooth&&g.entity.points.length>2){g.entity.points=smoothPoints(g.entity.points,g.strength,g.pointBudget);const record=meshes.get(g.entity.id);if(record)record.entity=null;}
  if(g.kind==='draw'&&g.entity.points.length>2&&$('profile').value==='taper'){const e=g.entity,n=e.points.length;e.points=e.points.map((p,i)=>[...p.slice(0,3),Math.max(.1,p[3]*Math.min(1,.15+Math.min(i,n-1-i)/(n*.2)))]);const record=meshes.get(e.id);if(record)record.entity=null;}
  if(!g.changed){restore(g.before);if(g.error)notify(g.error,true);return;}try{const next=g.entity?assistedStrokeScene(g.before.entities,g.entity,g.paper,g.mirror,g.mirrorId):entities;commit(next,g.kind==='erase'?'Erase gesture':g.kind==='move'?'Move selection':names[g.kind]+(g.mirror&&g.mirror!=='off'?' + mirror':''),g.before,selected,g.entity?[g.entity.id,g.mirrorId]:undefined);}catch(error){restore(g.before);notify(error.message,true);}if(g.error)notify(g.error,true);
}
function cursor(event){const p=screenPoint(event),r=Number($('erase-size').value);$('eraser-cursor').hidden=tool!=='erase';Object.assign($('eraser-cursor').style,{left:p[0]+'px',top:p[1]+'px',width:2*r+'px',height:2*r+'px'});}
canvas.addEventListener('pointerdown',event=>{
  if(panoramaView){if(event.button===0&&!busy){canvas.focus({preventScroll:true});panoramaView.drag={id:event.pointerId,x:event.clientX,y:event.clientY};canvas.setPointerCapture(event.pointerId);}return;}
  if(busy||event.button!==0||tool==='orbit'||gesture)return;if(event.pointerType==='touch'&&!event.isPrimary)return;canvas.focus({preventScroll:true});if(game){playHit(pick(event));return;}if(tool==='select'){select(pick(event),event.shiftKey);return;}
  if(tool==='marquee'){startGesture('marquee',event,{add:event.shiftKey,subtract:event.ctrlKey||event.metaKey});return;}if(tool==='erase'){startGesture('erase',event,{scope:new Set(selected),mode:$('erase-mode').value,radius:Number($('erase-size').value)});updateErase(event);return;}
  if(tool==='move'){const id=pick(event);if(id&&!selected.has(id))select(id,event.shiftKey);if(!selected.size){notify('Select an object, then drag to move it.');return;}const pivot=new THREE.Vector3(...worldPivot()),plane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()),pivot),hit=hitPlane(event,plane,false);if(hit)startGesture('move',event,{plane,hit});return;}
  const plane=drawingPlane(),raw=hitPlane(event,plane),hit=raw?snappedInput(event,raw,['line','curve','rectangle','ellipse','block'].includes(tool)).point:null;if(!hit){notify(activePaper()?'Face the front of the sheet, then draw inside it. Edit active surface → Face sheet helps.':'Aim inside the map, or orbit to face the drawing plane.');return;}if(entities.length>=LIMITS.objects){notify('The phone-compatible limit is 80 objects.',true);return;}
  const mirrored=!!activePaper()&&$('mirror-strokes').value!=='off'&&['draw','line','curve','rectangle','ellipse'].includes(tool),capacity=strokeCapacity(entities,mirrored),minimum=({draw:1,line:2,curve:3,rectangle:5,ellipse:65})[tool]||0;if(capacity<minimum){notify(mirrored?'Not enough room for both mirrored strokes. Remove content or turn Mirror off.':'Not enough point budget for this stroke.',true);return;}
  if(tool==='draw'){const previousPoints=counts(entities).points;if(previousPoints>=LIMITS.points){notify('The scene has reached 4,000 points.',true);return;}const e=Object.assign(entity(),clone(brush));e.position=hit.toArray();e.normal=plane.normal.toArray();e.paperId=activePaper()?.id||'';if(e.paperId){e.pointSpace='surface';e.normal=[0,0,1];}e.surface=!!e.paperId||$('plane').value!=='view';startGesture('draw',event,{entity:e,plane,previousPoints,postSmooth:$('post-smooth').checked,strength:Number($('smooth-strength').value)/100});entities=[...entities,e];selected=new Set();appendPoint(event);return;}
  if(['line','curve','rectangle','ellipse','block'].includes(tool)){if(tool==='curve'&&LIMITS.points-counts(entities).points<3){notify('A curve needs at least three free stroke points.',true);return;}const depth=Number($('block-depth').value);if(tool==='block'&&(!Number.isFinite(depth)||depth<.02||depth>3)){notify('Block depth must be between 0.02 and 3 metres.',true);return;}startGesture(tool,event,{start:hit.toArray(),plane,basis:planeBasis(plane),style:{...clone(brush),paperId:tool==='block'?'':activePaper()?.id||'',pointSpace:tool!=='block'&&activePaper()?'surface':'object'},depth,bend:Number($('curve-bend').value)/100,curveKind:$('curve-kind').value,pointBudget:capacity,id:crypto.randomUUID()});return;}
  const e=entity(tool);e.position=snapPoint(hit).toArray();e.color=argb(({start:'#7ee8c5',checkpoint:'#a99cf5',goal:'#ffa467'})[tool]);if(['start','goal'].includes(tool)&&entities.some(item=>item.type===tool)){notify('The map already has this marker. Select it to move it.');return;}try{commit([...entities,e],names[tool]);}catch(error){notify(error.message,true);}
});
canvas.addEventListener('pointermove',event=>{if(panoramaView){const d=panoramaView.drag;if(d?.id===event.pointerId){panoramaView.yaw-=(event.clientX-d.x)*Math.PI/canvas.clientWidth;panoramaView.pitch+=(event.clientY-d.y)*Math.PI/canvas.clientHeight;d.x=event.clientX;d.y=event.clientY;updatePanorama();}return;}cursor(event);if((!gesture||gesture.kind==='draw')&&activePaper()&&['draw','line','curve'].includes(tool)){const p=hitPlane(event,drawingPlane());if(p)snappedInput(event,p);else $('snap-cursor').hidden=true;}updateGesture(event);});canvas.addEventListener('pointerup',event=>{if(panoramaView){panoramaView.drag=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);return;}if(gesture?.pointerId!==event.pointerId)return;if(gesture.kind==='draw')appendPoint(event,true);else if(gesture.kind!=='erase')updateGesture(event);finishGesture();});canvas.addEventListener('pointercancel',()=>{if(panoramaView)panoramaView.drag=null;finishGesture(true);});canvas.addEventListener('lostpointercapture',()=>{if(panoramaView)panoramaView.drag=null;if(gesture)finishGesture();});canvas.addEventListener('pointerleave',()=>{$('eraser-cursor').hidden=true;$('snap-cursor').hidden=true;});canvas.addEventListener('contextmenu',event=>event.preventDefault());window.addEventListener('blur',()=>finishGesture());
function changeBrush(key,value){if(game)return;brush[key]=value;if(selected.size)editSelected('Change '+key,e=>e[key]=value,e=>e.type==='stroke'||['color','alpha'].includes(key)&&['block','image'].includes(e.type));updateInspector();}
$$('[data-brush]').forEach(b=>b.onclick=()=>changeBrush('brush',b.dataset.brush));$$('[data-color]').forEach(b=>b.onclick=()=>changeBrush('color',argb(b.dataset.color)));$('color').onchange=()=>changeBrush('color',argb($('color').value));$('pattern').onchange=()=>changeBrush('pattern',$('pattern').value);$('width').oninput=()=>$('width-value').textContent=$('width').value+' mm';$('width').onchange=()=>changeBrush('width',Number($('width').value)/1000);$('opacity').oninput=()=>$('opacity-value').textContent=$('opacity').value+'%';$('opacity').onchange=()=>changeBrush('alpha',Number($('opacity').value)/100);$('wet').onchange=()=>changeBrush('wet',$('wet').checked);$('smoothing').oninput=()=>$('smoothing-value').textContent=$('smoothing').value+'%';$('erase-size').oninput=()=>$('erase-value').textContent=$('erase-size').value+' px';
$('curve-bend').oninput=()=>$('curve-bend-value').textContent=$('curve-bend').value+'%';$('smooth-strength').oninput=()=>$('smooth-strength-value').textContent=$('smooth-strength').value+'%';
$('smooth-selected').onclick=()=>{if(game||busy)return;finishGesture();try{let spare=LIMITS.points-counts(entities).points,changed=false;const next=entities.map(e=>{if(!selected.has(e.id)||e.type!=='stroke'||e.points.length<3)return e;const points=smoothPoints(e.points,Number($('smooth-strength').value)/100,Math.min(LIMITS.stroke,e.points.length+spare));spare-=points.length-e.points.length;changed=true;return {...e,points};});if(changed)commit(next,'Smooth selected strokes');}catch(error){notify(error.message,true);}};
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('plane').onchange=()=>{if(tool==='block'&&$('plane').value==='view'){$('plane').value='wall';notify('Solid blocks use Wall, Floor or Side planes.');}updateGuide();};$('offset').oninput=updateGuide;
for(const [i,axis] of ['x','y','z'].entries()){
  $('pos-'+axis).onchange=()=>{if(game||busy)return;const before=pivotOf(entities,selected),move=[0,0,0];move[i]=Number($('pos-'+axis).value)-before[i];try{commit(transformSelection(entities,selected,{move}),'Move selection');}catch(error){notify(error.message,true);updateInspector();}};
  $('size-'+axis).onchange=()=>editSelected('Resize block',e=>e.size[i]=Number($('size-'+axis).value),e=>e.type==='block');
}
for(const key of ['yaw','scale'])$(key).onchange=()=>{if(game||busy)return;const e=selectedEntity(),value=Number($(key).value),change=key==='yaw'?{yaw:value-(e?.yaw||0)}:{scale:value/(e?.scale||1)};try{commit(transformSelection(entities,selected,change),key==='yaw'?'Rotate selection':'Scale selection');}catch(error){notify(error.message,true);updateInspector();}};
$('arc').oninput=()=>$('arc-value').textContent=$('arc').value+'°';$('arc').onchange=()=>editSelected('Curve image',e=>e.arc=Number($('arc').value),e=>e.type==='image');$('panel-width').onchange=()=>editSelected('Resize image',e=>e.panelWidth=Number($('panel-width').value),e=>e.type==='image');
$('delete').onclick=()=>{if(selected.size&&!game&&!busy){finishGesture();const removed=attachedIds(entities,selected);commit(entities.filter(e=>!removed.has(e.id)),'Delete selection');}};$('duplicate').onclick=()=>{if(!selected.size||game||busy)return;try{finishGesture();const result=duplicateSelection(entities,selected);commit(result.entities,'Duplicate selection',snapshot(),result.selected);}catch(error){notify(error.message,true);}};$('deselect').onclick=()=>select(null);$('undo').onclick=()=>travelHistory(true);$('redo').onclick=()=>travelHistory(false);
function setView(view){leavePanorama();finishGesture();controls.target.set(0,1.4,0);camera.up.set(0,1,0);if(view==='front')camera.position.set(0,1.4,5);else if(view==='perspective')camera.position.set(3.8,3.2,4.8);else{camera.position.set(0,6,.001);controls.target.set(0,0,0);$('plane').value='floor';}camera.position.sub(controls.target).multiplyScalar(Math.max(1,1/camera.aspect)).add(controls.target);controls.update();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));updateGuide();}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('fit').onclick=()=>{leavePanorama();finishGesture();const bounds=new THREE.Box3();for(const [id,r] of meshes)if(r.mesh.visible&&(!selected.size||selected.has(id)))bounds.union(new THREE.Box3().setFromObject(r.mesh));if(bounds.isEmpty()){setView('front');return;}const sphere=bounds.getBoundingSphere(new THREE.Sphere()),direction=camera.position.clone().sub(controls.target).normalize(),distance=Math.max(.5,sphere.radius/Math.sin(24*Math.PI/180)*Math.max(1,1/camera.aspect)*1.15);controls.target.copy(sphere.center);camera.position.copy(sphere.center).addScaledVector(direction,Math.min(20,distance));controls.update();requestFrame();};
function permitReplace(){return !dirty||confirm('This scene has edits that have not been exported. Replace it?');}
async function openText(text,name){const next=decode(text),prepared=await prepareImages(next,images);if(!permitReplace())return;stopGame();entities=next;images=prepared;history.clear();selected=new Set();projectName=name.replace(/\.json$/i,'');setDirty(false);syncMeshes();updateUI();setView('front');notify('Project opened. Strokes, shapes and images remain editable.');}
$('new').onclick=()=>{if(busy||!permitReplace())return;leavePanorama();finishGesture(true);stopGame();entities=[];images=new Map();history.clear();selected=new Set();projectName='Untitled scene';setDirty(false);syncMeshes();setView('front');setTool('draw');};$('open').onclick=()=>$('project-file').click();$('project-file').onchange=event=>{const file=event.target.files[0];event.target.value='';if(file)exclusive(async()=>{if(file.size>LIMITS.bytes)throw new Error('Project exceeds the 16 MiB file limit.');await openText(await file.text(),file.name);});};$('example').onclick=()=>exclusive(async()=>{const response=await fetch('./starter-map.json');if(!response.ok)throw new Error('Starter scene is unavailable.');await openText(await response.text(),'Starter scene');});
$('export').onclick=()=>{if(busy)return;finishGesture();try{const text=encode(entities),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=(projectName==='Untitled scene'?'draw-in-3d':projectName.replace(/[^\w .-]/g,'_'))+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setDirty(false);notify(versionOf(entities)===5?'Exported ink with hidden guides. Open with Android app v0.6 or newer.':versionOf(entities)===4?'Exported curved surfaces. Open with Android app v0.5 or newer.':versionOf(entities)===3?'Exported paper scene. Open it in Android app v0.3 or newer.':versionOf(entities)===2?'Exported. Blocks and patterned strokes require Android app v0.2 or newer.':'Download started. Import the JSON in the Android app.');}catch(error){notify(error.message,true);}};
$('edit-surface').onclick=()=>{if(!activePaper()||busy||game)return;const id=activePaperId;setTool('select');select(id);$('selection-panel').scrollIntoView({block:'nearest',behavior:'smooth'});};
$('paint-surface').onclick=()=>setTool('draw');
$('see-through').onchange=()=>{finishGesture();if($('see-through').checked)$('focus-sheet').checked=false;updateUI();};
$('mirror-strokes').onchange=()=>{finishGesture();updateVisibility();requestFrame();};
$('snap-ends').onchange=()=>{finishGesture();$('snap-cursor').hidden=true;};
function shiftSheet(sign,copy=false){
  if(busy||game||!activePaper())return;leavePanorama();finishGesture();const p=activePaper(),step=Number($('sheet-step').value)*sign,delta=camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(-step).toArray();
  try{
    if(copy){const e={...clone(p),id:crypto.randomUUID(),paperVisible:true,points:[],position:p.position.map((v,i)=>v+delta[i])};validate(documentOf([...entities,e]));$('focus-sheet').checked=false;$('see-through').checked=true;commit([...entities,e],'Add parallel sheet',snapshot(),new Set(),undefined,e.id);setTool('draw');notify('Blank parallel sheet added. The previous ink is visible through the guide.');}
    else commit(transformSelection(entities,new Set([p.id]),{move:delta}),'Move sheet depth');
  }catch(error){notify(error.message,true);}
}
$('sheet-nearer').onclick=()=>shiftSheet(1);$('sheet-farther').onclick=()=>shiftSheet(-1);$('parallel-sheet').onclick=()=>shiftSheet(1,true);
function setPaperVisibility(ids,visible,label){
  if(busy||game)return;leavePanorama();finishGesture();
  const next=entities.map(e=>e.type==='paper'&&ids.has(e.id)&&e.paperVisible!==visible?{...e,paperVisible:visible}:e);
  if(next.some((e,i)=>e!==entities[i]))commit(next,label);
}
$('toggle-paper').onclick=()=>{const p=activePaper();if(p)setPaperVisibility(new Set([p.id]),p.paperVisible===false,p.paperVisible===false?'Show paper sheet':'Hide sheet, keep ink');};
$('view-ink').onclick=()=>{if(busy||game)return;setPaperVisibility(new Set(entities.filter(e=>e.type==='paper').map(e=>e.id)),false,'Hide all sheets, keep ink');$('focus-sheet').checked=false;$('workspace-guides').checked=false;selected=new Set();setTool('orbit');notify('Drag to orbit your 3D ink. Add a sheet from this view to draw in another direction.');};
$('show-papers').onclick=()=>setPaperVisibility(new Set(entities.filter(e=>e.type==='paper').map(e=>e.id)),true,'Show all paper sheets');
$('workspace-guides').onchange=()=>{updateGuide();updateVisibility();requestFrame();};
$('surface-bend').oninput=()=>$('surface-bend-value').textContent=$('surface-bend').value+'°';
for(const key of ['bend','pitch','roll'])$('surface-'+key).onchange=()=>editSelected('Change surface '+key,e=>e[key]=Number($('surface-'+key).value),e=>e.type==='paper');
$('flatten-surface').onclick=()=>editSelected('Flatten surface',e=>e.bend=0,e=>e.type==='paper');
function facePaper(p){leavePanorama();if(!p)return;const n=rotate(paperAxes(p).n,p.yaw);controls.target.fromArray(p.position);camera.position.copy(controls.target).addScaledVector(new THREE.Vector3(...n),Math.max(1,p.panelWidth*p.scale*1.5)*Math.max(1,1/camera.aspect));camera.up.fromArray(rotate(paperAxes(p).v,p.yaw));controls.update();requestFrame();}
$('face-surface').onclick=()=>facePaper(selectedEntity()?.type==='paper'?selectedEntity():activePaper());
$('face-and-draw').onclick=()=>{if(busy||game)return;facePaper(activePaper());setTool('draw');};
$('focus-sheet').onchange=()=>{updateVisibility();updateSelectionBox();requestFrame();};
$('show-all-sheets').onclick=()=>{$('focus-sheet').checked=false;updateVisibility();updateSelectionBox();requestFrame();};
function bendActivePaper(value){if(busy||game||!activePaper())return;leavePanorama();finishGesture();try{const id=activePaperId,next=localizePapers(entities,new Set([id])).map(e=>e.id===id?{...e,bend:value}:e);commit(next,'Curve paper sheet');}catch(error){notify(error.message,true);updateInspector();}}
$$('[data-paper-bend]').forEach(b=>b.onclick=()=>bendActivePaper(Number(b.dataset.paperBend)));
$('active-paper-bend').oninput=()=>$('active-paper-bend-value').textContent=$('active-paper-bend').value+'°';
$('active-paper-bend').onchange=()=>bendActivePaper(Number($('active-paper-bend').value));
function updatePanorama(){const p=panoramaView;if(!p)return;p.yaw=THREE.MathUtils.clamp(p.yaw,-p.limit,p.limit);p.pitch=THREE.MathUtils.clamp(p.pitch,-1.15,1.15);const direction=p.u.clone().multiplyScalar(Math.sin(p.yaw)*Math.cos(p.pitch)).addScaledVector(p.v,Math.sin(p.pitch)).addScaledVector(p.n,-Math.cos(p.yaw)*Math.cos(p.pitch));camera.up.copy(p.v);camera.lookAt(camera.position.clone().add(direction));requestFrame();}
function leavePanorama(){const p=panoramaView;if(!p)return;panoramaView=null;if(p.drag&&canvas.hasPointerCapture(p.drag.id))canvas.releasePointerCapture(p.drag.id);camera.position.copy(p.position).sub(p.target).multiplyScalar(Math.max(1,1/camera.aspect)/Math.max(1,1/p.aspect)).add(p.target);camera.up.copy(p.up);camera.fov=p.fov;camera.updateProjectionMatrix();controls.target.copy(p.target);controls.enabled=!busy;controls.update();tool=p.tool;setTool(p.tool,true);selected=new Set([...p.selected].filter(id=>entities.some(e=>e.id===id)));updateUI();updateVisibility();updateSelectionBox();requestFrame();}
$('preview-panorama').onclick=()=>{if(busy||game||panoramaView)return;finishGesture();const p=activePaper();if(!p||p.bend<30)return;const axes=paperAxes(p),state={position:camera.position.clone(),up:camera.up.clone(),target:controls.target.clone(),fov:camera.fov,aspect:camera.aspect,tool,selected:new Set(selected),yaw:0,pitch:0,limit:Math.min(Math.PI,p.bend*Math.PI/360+.15),u:new THREE.Vector3(...rotate(axes.u,p.yaw)),v:new THREE.Vector3(...rotate(axes.v,p.yaw)),n:new THREE.Vector3(...rotate(axes.n,p.yaw))};setTool('panorama');panoramaView=state;selected=new Set();controls.enabled=false;camera.position.fromArray(p.position).addScaledVector(state.n,p.panelWidth/(p.bend*Math.PI/180)*p.scale);camera.fov=75;camera.updateProjectionMatrix();updatePanorama();updateUI();};
$('exit-panorama').onclick=()=>leavePanorama();
$('painting-target').onchange=()=>{if(game||busy)return;finishGesture();activePaperId=$('painting-target').value;setTool('draw');updateGuide();};
Object.entries(PAPER_TYPES).forEach(([key,value])=>$('paper-kind').add(new Option(value.name,key)));
$('paper-kind').onchange=()=>{if(game||busy)return;const kind=$('paper-kind').value;leavePanorama();finishGesture();const p=selectedEntity()?.type==='paper'?selectedEntity():activePaper();if(p)commit(entities.map(e=>e.id===p.id?{...e,paperKind:kind}:e),'Change paper finish');else updateInspector();};
$('add-paper').onclick=()=>{if(game||busy)return;leavePanorama();finishGesture();try{const papers=entities.filter(e=>e.type==='paper'),keepContext=papers.length>0&&papers.every(e=>e.paperVisible===false);camera.updateMatrixWorld();const e=entity('paper'),facingView=$('paper-placement').value==='view',plane=facingView?new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()).negate(),controls.target):mapPlane();e.position=plane.projectPoint(controls.target,new THREE.Vector3()).toArray();const normal=plane.normal.clone();if(normal.dot(camera.position.clone().sub(new THREE.Vector3(...e.position)))<0)normal.negate();e.normal=normal.toArray();if(facingView){const axes=basis(e.normal),right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0);e.roll=Math.atan2(right.dot(new THREE.Vector3(...axes.v)),right.dot(new THREE.Vector3(...axes.u)))*180/Math.PI;}e.paperKind=$('paper-kind').value;e.panelWidth=2.4;e.aspect=1.5;e.color=argb('#ffffff');commit([...entities,e],'Add paper',snapshot(),new Set(),undefined,e.id);$('focus-sheet').checked=!keepContext&&!$('see-through').checked;if(!papers.length)Object.assign(brush,{brush:'Water',color:argb('#3974b8'),width:.06,alpha:.85,wet:true});setTool('draw');notify(keepContext?'New sheet ready. Your other ink stays visible for reference.':'New sheet ready to draw. Focus sheet hides other objects; Show all objects restores the scene.');}catch(error){notify(error.message,true);}};
for(const key of ['width','height'])$('paper-'+key).onchange=()=>editSelected('Resize paper',e=>{const width=Number($('paper-width').value),height=Number($('paper-height').value);if(!Number.isFinite(height)||height<.1||height>4)throw new Error('Paper height must be 0.1–4 metres.');e.panelWidth=width;e.aspect=width/height;},e=>e.type==='paper');
$('add-image').onclick=()=>{if(game)stopGame();$('image-file').click();};$('image-file').onchange=event=>{const file=event.target.files[0];event.target.value='';if(!file)return;exclusive(async()=>{const c=counts(entities);if(c.images>=LIMITS.images||c.objects>=LIMITS.objects)throw new Error('Image/object limit reached. Remove an object first.');const photo=await importPhoto(file),e=Object.assign(entity('image'),photo);e.position=controls.target.toArray();while(!withinBounds(e)&&e.panelWidth>.11)e.panelWidth=Math.max(.1,e.panelWidth*.8);if(!withinBounds(e))throw new Error('Move the view target nearer the origin first.');const next=[...entities,e];images=await prepareImages(next,images);$('focus-sheet').checked=false;commit(next,'Add image',snapshot(),new Set([e.id]));setTool('select',true);notify('Image added. Select it to adjust curvature, size and position.');});};
function stopGame(){if(!game)return;game=null;$('game-status').hidden=true;$('play').innerHTML='<span>▷</span> Play map';for(const r of meshes.values())r.mesh.material.color.set(0xffffff);guide.visible=true;updateUI();}
function nextMarker(){const id=game.ids[game.index];for(const [key,r] of meshes)r.mesh.material.color.set(key===id?0xffffff:game.ids.includes(key)?0x526a5e:0xffffff);$('game-status').textContent=game.index===0?'Tap Start to begin':game.index===game.ids.length?'Map complete ✓':game.index===game.ids.length-1?'Now tap Goal':`Tap Checkpoint ${game.index} of ${game.ids.length-2}`;requestFrame();}
function playHit(id){if(game&&id===game.ids[game.index]){game.index++;nextMarker();}}
$('play').onclick=()=>{if(game){stopGame();return;}finishGesture();const start=entities.filter(e=>e.type==='start'),goal=entities.filter(e=>e.type==='goal');if(start.length!==1||goal.length!==1){notify('Place exactly one Start and one Goal to play.');return;}setTool('select');game={ids:[start[0].id,...entities.filter(e=>e.type==='checkpoint').map(e=>e.id),goal[0].id],index:0};selected=new Set();guide.visible=false;$('welcome').hidden=true;$('game-status').hidden=false;$('play').textContent='← Return to edit';updateUI();nextMarker();};$('help').onclick=()=>$('guide').showModal();$('close-guide').onclick=$('guide-done').onclick=()=>$('guide').close();
window.addEventListener('keydown',event=>{if(busy||$('guide').open||['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;const key=event.key.toLowerCase(),modifier=event.ctrlKey||event.metaKey;if(key==='escape'){if(panoramaView){leavePanorama();return;}if(gesture)finishGesture(true);else if(game)stopGame();else select(null);return;}if(panoramaView&&['arrowleft','arrowright','arrowup','arrowdown'].includes(key)){event.preventDefault();panoramaView.yaw+=key==='arrowleft'?-.12:key==='arrowright'?.12:0;panoramaView.pitch+=key==='arrowup'?.08:key==='arrowdown'?-.08:0;updatePanorama();return;}if(modifier&&key==='s'){event.preventDefault();$('export').click();return;}if(panoramaView&&((modifier&&!['z','y'].includes(key))||(!modifier&&!keys[key])))return;if(game)return;if(modifier&&key==='z'){event.preventDefault();travelHistory(!event.shiftKey);}else if(modifier&&key==='y'){event.preventDefault();travelHistory(false);}else if(modifier&&key==='a'){event.preventDefault();finishGesture();selected=new Set(entities.filter(e=>meshes.get(e.id)?.mesh.visible).map(e=>e.id));updateUI();}else if(modifier&&key==='d'){event.preventDefault();$('duplicate').click();}else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();$('delete').click();}else if(!modifier&&key==='f')$('fit').click();else if(!modifier&&keys[key])setTool(keys[key]);});
window.addEventListener('beforeunload',event=>{if(dirty||gesture?.changed){event.preventDefault();event.returnValue='';}});window.addEventListener('dragover',event=>event.preventDefault());window.addEventListener('drop',event=>{event.preventDefault();notify('Use Open project or Image to import your file.');});setTool('draw');updateGuide();updateUI();
